# Generated by Django 3.1.3 on 2020-11-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('u_name', models.CharField(max_length=32)),
                ('context', models.CharField(max_length=65536)),
            ],
        ),
    ]
