# Generated by Django 3.1.3 on 2020-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField(default=0)),
                ('u_name', models.CharField(max_length=32)),
                ('context', models.CharField(max_length=65536)),
            ],
        ),
    ]
